language: c
addons:
  apt:
    packages:
      - libmagickwand-dev
      - cmocka
before_install:
  - mkdir -p $HOME/dl $HOME/src/XIMEA_Linux_SP
  - wget -P $HOME/dl http://www.ximea.com/downloads/recent/XIMEA_Linux_SP.tgz
  - tar -C $HOME/src/XIMEA_Linux_SP -xzf $HOME/dl/XIMEA_Linux_SP.tgz
  - cd $HOME/src/XIMEA_Linux_SP/package
  - sed -i '/^udevadm/ d' scripts/install_steps
  - ./install
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
cache:
  directories:
    - $HOME/src
