language: c
addons:
  apt:
    packages:
      - libmagickwand-dev
      - cmocka
before_install:
  - mkdir -p $HOME/dl $HOME/.local/lib
  - wget -P $HOME/dl http://www.ximea.com/downloads/recent/XIMEA_Linux_SP.tgz
  - tar -C $HOME/.local/lib -xvzf XIMEA_Linux_SP.tgz --strip-components=3 package/api/X64
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
cache:
  directories:
    - $HOME/dl
